// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvwbfzktkxrzijqpwdzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12d2Jmemt0a3hyemlqcXB3ZHpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNTEzOTAsImV4cCI6MjA2MDYyNzM5MH0.HS_CzWPdtGFrufzdRdAkhB-Sy0epwXtRIwPL2EE6FYM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);